<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTtjHiKZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTtjHiKZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTtjHiKZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTtjHiKZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTtjHiKZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'TtjHiKZ',
    'container.build_id' => '9cb257d7',
    'container.build_time' => 1683187349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTtjHiKZ');
